- value: initial
  pose2D:
      x: 0.0
      y: 0.0
      theta: 0.0

- value: lamp-location
  pose2D:
      x: 1.0
      y: 1.0
      theta: 0.80

- value: door-location
  pose2D:
      x: 2.0
      y: 2.0
      theta: 1.57